---
clusters:
  roci:
    inputpath: "ro_squeue_future_noNA.csv"
    outputpath: "/Users/vhafener/Repos/LiveGantt/Charts/"
    timeframe: 48
    count: 508
    cache: False
    clear_cache: False
    projects_in_legend: False
    utilization: True
    coloration_set: 
      - default
